# Generated by Django 4.2.7 on 2023-11-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ombor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombor',
            name='ism',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='manzil',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='nom',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='soha',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ombor',
            name='tel',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
